atena/apps/contas/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [

    url(r'login/$', LoginView.as_view(), name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
    url(r'usuario/registrar-se/$', AutoCadastroUsuarioView.as_view(), name='autocadastro'),
    url(r'usuario/editar/(?P<pk>\d+)/$', EdicaoUsuarioView.as_view(),
        name='EdicaoUsuario'),
    url(r'usuario/profile/(?P<pk>\d+)/$', ProfileView.as_view(),
        name='Profile'),
]

atena/apps/main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import *

urlpatterns = [

    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^sucesso/$', SucessoView.as_view(), name='Sucesso'),
    url(r'^revisao/add/$', CadastroRevisaoView.as_view(), name='CadastroRevisao'),
    url(r'^revisao/lista/$', ListaRevisoesView.as_view(), name='ListaRevisoes'),
    url(r'^revisao/(?P<pk>\d+)/$', EdicaoRevisaoView.as_view(), name='EdicaoRevisao'),
    url(r'^revisao/(?P<pk>\d+)/artigos$', ListaDocumentosRevisaoView.as_view(), name='ListaDocumentosRevisao'),
    url(r'^revisao/(?P<pk>\d+)/documentos/(?P<pk_documento>\d+)/$', VisualizaDocumentoView.as_view(), name='VisualizarDocumento'),
    url(r'^revisao/(?P<revisao_pk>\d+)/documento/add/$', CadastroDocumentoRevisaoView.as_view(), name='CadastroDocumentoRevisao'),
    url(r'^revisao/(?P<pk>\d+)/documentos/importar/$', ImportarDocumentosView.as_view(), name='ImportarDocumentos'),
    url(r'^revisao/(?P<pk>\d+)/documentos/remover/$', RemoverDocumentoRevisaoView.as_view(), name='RemoverDocumentos'),
    url(r'^revisao/(?P<pk>\d+)/documentos/classificar/$', ClassificarDocumentosView.as_view(), name='ClassificarDocumentos'),
    url(r'^revisao/(?P<revisao_pk>\d+)/documento/fichamento/add/(?P<documento_pk>\d+)$',
        CadastroFichamentoView.as_view(), name='CadastroFichamento'),
    url(r'^revisao/(?P<revisao_pk>\d+)/documento/(?P<documento_pk>\d+)/fichamento/(?P<pk>\d+)$',
        EdicaoFichamentoView.as_view(), name='EdicaoFichamento'),

    url(r'^revisao/(?P<revisao_pk>\d+)/documentos/tags/add/$', CadastroTagView.as_view(), name='CadastroTag'),
    url(r'^revisao/(?P<revisao_pk>\d+)/documentos/tags/associar/$', AssociarTagView.as_view(), name='AssociarTag'),

]

atena/urls.py
"""atena URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
"""

from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^martor/', include('martor.urls')),
    url(r'^', include(('main.urls', 'main'), namespace='main')),
    url(r'^contas/', include(('contas.urls', 'contas'), namespace='contas')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'main.views.handler404'
handler403 = 'main.views.handler403'
handler500 = 'main.views.handler500'

atena/apps/base/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class BaseModel(models.Model):
    cadastrado_em = models.DateTimeField("Data de cadastrado", auto_now_add=True)
    cadastrado_por = models.ForeignKey('contas.Usuario', default=1, on_delete=models.CASCADE)
    atualizado_em = models.DateTimeField("Data da última atualizacao", auto_now=True)

    class Meta:
        abstract = True

atena/apps/base/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import re

from django import forms
from django.utils import timezone
from localflavor.br.forms import BRCPFField


class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.usuario = kwargs.pop('usuario')
        super(BaseForm, self).__init__(*args, **kwargs)
        if 'cadastrado_por' in self.fields:
            self.fields['cadastrado_por'].required = False

    def save(self, commit=True):
        objeto = super(BaseForm, self).save(commit=False)
        objeto.cadastrante = self.usuario
        if self.instance.id is not None:
            objeto.atualizado_em = timezone.now()

        if commit:
            objeto.save()
            self.save_m2m()

        return objeto


class BRCPFFieldUnique(BRCPFField):
    """
    Extende a classe BRCPFField para forçar valores
    únicos para o CPF e também para sempre salvar apenas
    os números na base de dados sem pontos e hífem.
    Usado no UserRegistrationForm que não extende o ModelForm
    e por isso ignora o fato do campo cpf estar marcado como único.
    """

    default_error_messages = {
        'invalid': "Número de CPF inválido.",
        'max_digits': "Este campo requer no máximo 11 dígitos ou 14 caracteres.",
    }

    def __init__(self, *args, **kwargs):
        super(BRCPFFieldUnique, self).__init__(*args, **kwargs)

    def clean(self, value):
        value = re.sub("[-\.]", "", value)

        if value == '00000000000':
            return value

        super(BRCPFFieldUnique, self).clean(value)

        return value


class RGField(forms.CharField):

    def clean(self, value):
        value = str(value)
        value = re.sub("[()-\.]", "", value)
        return value


class TelefoneField(RGField):
    pass

atena/apps/contas/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import authenticate

from base.forms import *
from .helpers import *
from .models import *


class LoginForm(forms.Form):
    cpf = forms.CharField(label='cpf', required=True)
    senha = forms.CharField(label='Senha', required=False)
    lembrar_me = forms.BooleanField(label="Manter conectado", required=False)

    def clean(self):
        if self.errors:
            return super(LoginForm, self).clean()

        usuarios = Usuario.objects.filter(cpf=self.cleaned_data['cpf'])
        self.usuario = authenticate(username=self.cleaned_data.get('cpf', None), password=self.cleaned_data['senha'])

        if usuarios.count() == 0:
            self.add_error('cpf', u'Nenhum usuário cadastrado com esse usuário')

        if (not self.usuario or not self.usuario.ativo == 1) and self.cleaned_data.get('cpf', None):
            self.add_error('senha', u'Senha incorreta')

        return super(LoginForm, self).clean()

    def obter_usuario(self):
        return self.usuario


class UsuarioForm(forms.ModelForm):
    senha = forms.CharField(label=u'Senha', widget=forms.PasswordInput)
    senha2 = forms.CharField(label=u'Confirmação da senha', widget=forms.PasswordInput)
    imagem = forms.ImageField(required=False)

    class Meta:
        model = Usuario
        exclude = ['password', 'ativo', 'admin', 'superusuario', 'last_login']

    def __init__(self, *args, **kwargs):
        super(UsuarioForm, self).__init__(*args, **kwargs)
        self.helper = UsuarioHelper()
        if self.instance.pk:
            self.fields['senha'].required = False
            self.fields['senha2'].required = False

    def clean_senha2(self):
        senha = self.cleaned_data["senha"]
        senha2 = self.cleaned_data["senha2"]
        if senha != senha2:
            raise forms.ValidationError(u"As senhas não são iguais")

    def save(self, commit=True):
        objeto = super(UsuarioForm, self).save(commit=False)
        if self.cleaned_data["senha"]:
            objeto.set_password(self.cleaned_data["senha"])

        if self.cleaned_data['imagem']:
            objeto.imagem = self.cleaned_data['imagem']

        if commit:
            objeto.save()

        return objeto

atena/apps/main/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from .helpers import RevisaoHelper, FichamentoHelper, SelecionarBaseHelper, DocumentoHelper
from .models import Revisao, Documento, Fichamento, Tag
from base.forms import BaseForm


class RevisaoForm(BaseForm):

    class Meta:
        model = Revisao
        exclude = ['adm', 'documentos']

    def __init__(self, *args, **kwargs):
        super(RevisaoForm, self).__init__(*args, **kwargs)
        self.helper = RevisaoHelper()

    def save(self, commit=True):
        revisao = super(RevisaoForm, self).save(commit=False)
        revisao.adm = self.usuario
        if commit:
            revisao.save()
            self.save_m2m()

            if self.usuario not in revisao.usuarios.all():
                revisao.usuarios.add(self.usuario)

        return revisao


class DocumentoForm(BaseForm):
    class Meta:
        model = Documento
        exclude = ['revisao','arquivo']

    def __init__(self, *args, **kwargs):
        self.revisao = kwargs.pop('revisao')
        super(DocumentoForm, self).__init__(*args, **kwargs)
        self.helper = DocumentoHelper()

    def save(self, commit=True):
        documento = super(DocumentoForm, self).save(commit=False)
        

        if commit:
            documento.save()
            self.save_m2m()
            if self.revisao: 
                self.revisao.documentos.add(documento)

        return documento


class FichamentoForm(BaseForm):

    class Meta:
        model = Fichamento
        exclude = ['documento', 'revisao']

    def __init__(self, *args, **kwargs):
        self.revisao = kwargs.pop('revisao')
        self.documento = kwargs.pop('documento')
        super(FichamentoForm, self).__init__(*args, **kwargs)
        self.fields['tags'].queryset = Tag.objects.filter(revisao=self.revisao)
        self.fields['tags'].required = False
        self.helper = FichamentoHelper()


    def save(self, commit=True):
        fichamento = super(FichamentoForm, self).save(commit=False)
        fichamento.documento = self.documento
        fichamento.revisao = self.revisao
        
        if commit:
            fichamento.save()
            self.save_m2m()


        return fichamento


class TagForm(BaseForm):
    class Meta:
        model = Tag
        fields = ['nome', 'cor']

    def __init__(self, *args, **kwargs):
        self.revisao = kwargs.pop('revisao')
        super(TagForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        tag = super(TagForm, self).save(commit=False)
        tag.revisao = self.revisao

        if commit:
            tag.save()

        return tag


class SelecionarBaseForm(forms.Form):
    termos_de_tecnologias = forms.CharField(required=False)
    termos_da_saude = forms.CharField(required=False)
    revistas = forms.CharField(required=False)
    ano_inicio = forms.IntegerField(required=False)
    ano_fim = forms.IntegerField(required=False)
    extra = forms.CharField(required=False)
    bases_de_pesquisa = forms.MultipleChoiceField(
        choices=(
            ('IEEE Xplore', 'IEEE Xplore'),
            ('Scopus', 'Scopus'),
            ('Web of Science', 'Web of Science'),
            ('Springer', 'Springer'),
            ('Science Direct', 'Science Direct'),
            ('PMC', 'PMC'),
            ('PubMed', 'PubMed')
        ),
        widget=forms.CheckboxSelectMultiple()
    )
    revisao = forms.IntegerField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super(SelecionarBaseForm, self).__init__(*args, **kwargs)
        self.helper = SelecionarBaseHelper()

atena/apps/base/views.py
# -*- coding: utf-8 -*-
from django.core.paginator import EmptyPage, PageNotAnInteger
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.base import TemplateView
from django.shortcuts import HttpResponseRedirect
from django.db import transaction

from base.diggpagination import DiggPaginator as Paginator
from .mixins import *


class BaseTemplateView(TemplateView):
    template = ""
    titulo_pagina = ""
    subtitulo_pagina = ""

    def get_context_data(self, **kwargs):
        self.template_name = self.template
        context = super(BaseTemplateView, self).get_context_data(**kwargs)
        context['titulo_pagina'] = self.titulo_pagina
        context['subtitulo_pagina'] = self.subtitulo_pagina

        return context


class BaseFormView(LoginRequiredMixin, CreateView):
    template_name = 'main/cadastro.html'
    subtitulo_pagina = 'Cadastrar'
    success_url = '/sucesso/'

    def get_context_data(self, **kwargs):
        context = super(BaseFormView, self).get_context_data(**kwargs)
        context['titulo_pagina'] = self.titulo_pagina
        context['subtitulo_pagina'] = self.subtitulo_pagina
        return context

    def get_form_kwargs(self):
        kwargs = super(BaseFormView, self).get_form_kwargs()
        kwargs.update({'usuario': self.request.user})

        return kwargs

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        return super(BaseFormView, self).post(request, *args, **kwargs)


class BaseUpdateView(BaseFormView, UpdateView):
    subtitulo_pagina = ''

    def post(self, request, *args, **kwargs):
        if request.POST.get('reset', None) == 'Excluir':
            self.get_object().delete()
            return HttpResponseRedirect(self.success_url)

        else:
            return super(BaseUpdateView, self).post(request, *args, **kwargs)


class BaseListView(LoginRequiredMixin, TemplateView):
    template_name = "base/lista.html"
    subtitulo_pagina = "Lista"
    filtro = None
    entrada_atual_filtro = ""
    queryset = []
    paginate_by = 64
    titulo_pagina = ""

    def get_queryset(self):
        return self.queryset

    def get(self, *args, **kwargs):
        if self.filtro:
            filtro = self.filtro(self.request.GET or None, queryset=self.get_queryset())
            if filtro.is_valid():
                self.queryset = filtro.pesquisar()
                self.entrada_atual_filtro = filtro['entrada'].value()
            else:
                self.queryset = self.get_queryset()

        return super(BaseListView, self).get(*args, **kwargs)


    def get_context_data(self, **kwargs):
        paginator = Paginator(self.get_queryset(), self.paginate_by, tail=4, body=3)
        pagina = self.request.GET.get('pagina', 1)

        try:
            lista = paginator.page(pagina)
        except PageNotAnInteger:
            lista = paginator.page(1)
        except EmptyPage:
            lista = paginator.page(paginator.num_pages)

        GET_params = self.request.GET.copy()
        if 'pagina' in GET_params.keys():
            del GET_params['pagina']

        return {
            'GET_params': GET_params,
            'lista': lista,
            'filtro': self.filtro,
            'entrada_atual_filtro': self.entrada_atual_filtro,
            'titulo_pagina': self.titulo_pagina,
        }

atena/apps/contas/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic import FormView, RedirectView
from django.views.generic.edit import CreateView
from django.shortcuts import get_object_or_404
from django.contrib.auth import login, logout
from django.utils.http import is_safe_url
from django.shortcuts import render

from base.views import BaseFormView, BaseUpdateView, TemplateView
from base.mixins import LoginRequiredMixin
from .forms import LoginForm, UsuarioForm
from .models import Usuario

class LoginView(FormView):
    template_name = 'contas/login.html'
    form_class = LoginForm
    success_url = '/'
    redirect_field_name = 'next'

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        return context

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)

        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url

        return redirect_to

    def form_valid(self, form):
        if form.is_valid():
            if not form.cleaned_data['lembrar_me']:
                self.request.session.set_expiry(0)
            login(self.request, form.obter_usuario())
        return super(LoginView, self).form_valid(form)


class LogoutView(LoginRequiredMixin, RedirectView):
    url = '/contas/login/'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class CadastroUsuarioView(BaseFormView):
    titulo_pagina = "Usuário"
    subtitulo_pagina = 'Cadastrar'
    model = Usuario
    form_class = UsuarioForm


class AutoCadastroUsuarioView(CreateView):
    template_name = 'contas/registrar-se.html'
    model = Usuario
    form_class = UsuarioForm
    success_url = '/'


class EdicaoUsuarioView(CadastroUsuarioView, BaseUpdateView):
    subtitulo_pagina = 'Editar'

    def get_queryset(self):
        if self.request.user.has_group('Administrador'):
            return Usuario.objects.all()
        else:
            return Usuario.objects.filter(id=self.request.user.id)


class ProfileView(TemplateView):
    template_name = 'contas/profile.html'

    def get_object(self):
        return get_object_or_404(Usuario, id=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)

        context.update({
            'obj': self.get_object(),
        })

        return context

atena/templates/base/includes/head.html
{% load staticfiles %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'admin-lte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'admin-lte/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'admin-lte/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'admin-lte/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'admin-lte/dist/css/skins/_all-skins.min.css' %}">
  <!-- Morris chart -->
  <link rel="stylesheet" href="{% static 'admin-lte/bower_components/morris.js/morris.css' %}">
  <!-- jvectormap -->
  <link rel="stylesheet" href="{% static 'admin-lte/bower_components/jvectormap/jquery-jvectormap.css' %}">
  <!-- Date Picker -->
  <link rel="stylesheet" href="{% static 'admin-lte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'admin-lte/bower_components/bootstrap-daterangepicker/daterangepicker.css' %}">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
  <!-- select2 -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/select2/css/select2.min.css' %}">
  <!-- Datetimepicker -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  <!-- Custom GEMA Style -->
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">

atena/templates/base/includes/header.html
{% load staticfiles %}
<!-- Logo -->
<a href="{% url 'main:index' %}" class="logo">
  <!-- mini logo for sidebar mini 50x50 pixels -->
  <span class="logo-mini"><i class="fa fa-search"></i></span>
  <!-- logo for regular state and mobile devices -->
  <span class="logo-lg"><b> <i class="fa fa-search"></i> Atena </b></span>
</a>
<!-- Header Navbar: style can be found in header.less -->
<nav class="navbar navbar-static-top">
  <!-- Sidebar toggle button-->
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
    <span class="sr-only">Toggle navigation</span>
  </a>

  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">

      <li class="dropdown notifications-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
          <i class="fa fa-bell-o"></i>
          <span class="label label-warning">0</span>
        </a>
        <ul class="dropdown-menu">
          <li id="notificacoes-cnt" class="header">Você tem 0 notificações</li>
          <li>
            <!-- inner menu: contains the actual data -->
            <ul class="menu">

            </ul>
          </li>
          <li class="footer"><a href="#">Ver todas</a></li>
        </ul>
      </li>

      <!-- User Account: style can be found in dropdown.less -->
      <li class="dropdown user user-menu">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          {% if request.user.imagem %}
            <img src="{{ request.user.imagem.url }}" alt="Imagem de perfil do usuário" class="user-image">
          {% else %}
            <img src="{% static 'img/user-img-default.png' %}" alt="Imagem de perfil do usuário" class="user-image">
          {% endif %}
          <span class="hidden-xs">{{ request.user.username }}</span>
        </a>
        <ul class="dropdown-menu">
          <!-- User image -->
          <li class="user-header">
            {% if request.user.imagem %}
              <img src="{{ request.user.imagem.url }}" alt="Imagem de perfil do usuário" class="img-circle">
            {% else %}
              <img src="{% static 'img/user-img-default.png' %}" alt="Imagem de perfil do usuário" class="img-circle">
            {% endif %}

            <p>
              {{ request.user.username }}
              <small>
              </small>
            </p>
          </li>
          <!-- Menu Body -->
          <li class="user-body">
            <div class="row">
              <div class="col-xs-4 text-center">
                <a href="#">Equipe</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Rede</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Casos</a>
              </div>
            </div>
            <!-- /.row -->
          </li>
          <!-- Menu Footer-->
          <li class="user-footer">
            <div class="pull-left">
              <a href="" class="btn btn-default btn-flat">Perfil</a>
            </div>
            <div class="pull-right">
              <a href="{% url 'contas:logout' %}" class="btn btn-default btn-flat">Sair</a>
            </div>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

atena/templates/base/includes/sidebar.html
{% load staticfiles %}
{% load perms %}
<!-- sidebar menu -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          {% if request.user.imagem %}
          <img src="{{ request.user.imagem.url }}" alt="Imagem de perfil do usuário" class="img-circle">
          {% else %}
          <img src="{% static 'img/user-img-default.png' %}" alt="Imagem de perfil do usuário" class="img-circle">
          {% endif %}
        </div>
        <div class="pull-left info">
          <p>{{ request.user.username }}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>


      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Ações</li>
        <li class="active treeview">

        </li>

        <li>
          <a href="{% url 'main:ListaRevisoes' %}">
            <i class="fa fa-folder-open-o"></i> <span>Minhas revisões</span>
          </a>
          <a href="{% url 'main:CadastroRevisao' %}">
            <i class="fa  fa-plus-square-o"></i> <span>Começar nova</span>
          </a>

        </li>

        <li class="header">Dúvidas, Sugestões ou Reclamações </li>
        <li>
          <a href="">
            <i class="fa fa-headphones"></i> <span>Contate-nos</span>
          </a>

        </li>

      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>
<!-- /sidebar menu -->

atena/templates/base/includes/small_modal.html
<div class="modal-dialog modal-md">
  <div class="modal-content">

    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
      </button>
      <h4 class="modal-title" id="myModalLabel2">{{ titulo_modal }} </h4>
    </div>
    <div class="modal-body">
      <h4>{{ subtitulo_modal }} {{ subtitulo_modal2 }}</h4>
      <p> {{ texto_modal }} </p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">fechar</button>
    </div>

  </div>
</div>

atena/templates/base/includes/top_nav.html
{% load staticfiles %}
<!-- top navigation -->
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">

              {% if request.user.imagem %}
                  <img src="{{ request.user.imagem.url }}" alt="">{{ request.user.username }}
            {% else %}
                <img src="{% static 'img/user-img-default.png' %}" alt="">{{ request.user.username }}
            {% endif %}
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="{% url 'contas:EdicaoUsuario' request.user.id %}"> Perfil</a></li>
            <li>
              <a href="javascript:;">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li><a href="javascript:;">Help</a></li>
            <li><a href="/contas/logout"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
          </ul>
        </li>

        <li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">6</span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
              <a>
                <span class="image"><img src="{% static 'img/user-img-default.png' %}" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><img src="{% static 'img/user-img-default.png' %}" alt="Profile Image" /></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <div class="text-center">
                <a>
                  <strong>See All Alerts</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>
<!-- /top navigation -->