atena/apps/contas/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [

    url(r'login/$', LoginView.as_view(), name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
    url(r'usuario/registrar-se/$', AutoCadastroUsuarioView.as_view(), name='autocadastro'),
    url(r'usuario/editar/(?P<pk>\d+)/$', EdicaoUsuarioView.as_view(),
        name='EdicaoUsuario'),
    url(r'usuario/profile/(?P<pk>\d+)/$', ProfileView.as_view(),
        name='Profile'),
]

atena/apps/main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import *

urlpatterns = [

    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^sucesso/$', SucessoView.as_view(), name='Sucesso'),
    url(r'^revisao/add/$', CadastroRevisaoView.as_view(), name='CadastroRevisao'),
    url(r'^revisao/lista/$', ListaRevisoesView.as_view(), name='ListaRevisoes'),
    url(r'^revisao/(?P<pk>\d+)/$', EdicaoRevisaoView.as_view(), name='EdicaoRevisao'),
    url(r'^revisao/(?P<pk>\d+)/artigos$', ListaDocumentosRevisaoView.as_view(), name='ListaDocumentosRevisao'),
    url(r'^revisao/(?P<pk>\d+)/documentos/(?P<pk_documento>\d+)/$', VisualizaDocumentoView.as_view(), name='VisualizarDocumento'),
    url(r'^revisao/(?P<revisao_pk>\d+)/documento/add/$', CadastroDocumentoRevisaoView.as_view(), name='CadastroDocumentoRevisao'),
    url(r'^revisao/(?P<pk>\d+)/documentos/importar/$', ImportarDocumentosView.as_view(), name='ImportarDocumentos'),
    url(r'^revisao/(?P<pk>\d+)/documentos/remover/$', RemoverDocumentoRevisaoView.as_view(), name='RemoverDocumentos'),
    url(r'^revisao/(?P<pk>\d+)/documentos/classificar/$', ClassificarDocumentosView.as_view(), name='ClassificarDocumentos'),
    url(r'^revisao/(?P<revisao_pk>\d+)/documento/fichamento/add/(?P<documento_pk>\d+)$',
        CadastroFichamentoView.as_view(), name='CadastroFichamento'),
    url(r'^revisao/(?P<revisao_pk>\d+)/documento/(?P<documento_pk>\d+)/fichamento/(?P<pk>\d+)$',
        EdicaoFichamentoView.as_view(), name='EdicaoFichamento'),

    url(r'^revisao/(?P<revisao_pk>\d+)/documentos/tags/add/$', CadastroTagView.as_view(), name='CadastroTag'),
    url(r'^revisao/(?P<revisao_pk>\d+)/documentos/tags/associar/$', AssociarTagView.as_view(), name='AssociarTag'),

]

atena/urls.py
"""atena URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
"""

from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^martor/', include('martor.urls')),
    url(r'^', include(('main.urls', 'main'), namespace='main')),
    url(r'^contas/', include(('contas.urls', 'contas'), namespace='contas')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'main.views.handler404'
handler403 = 'main.views.handler403'
handler500 = 'main.views.handler500'

atena/apps/base/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class BaseModel(models.Model):
    cadastrado_em = models.DateTimeField("Data de cadastrado", auto_now_add=True)
    cadastrado_por = models.ForeignKey('contas.Usuario', default=1, on_delete=models.CASCADE)
    atualizado_em = models.DateTimeField("Data da última atualizacao", auto_now=True)

    class Meta:
        abstract = True

atena/apps/main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from contas.models import Usuario
from base.models import BaseModel
import reversion


#data_conferencia=)
from martor.models import MartorField


class Base(models.Model):
    # Constantes apontam para o ID de cada classe (preenchidas automaticamente por uma fixture)
    IEEE_XPLORE = 1
    SCIENCE_DIRECT = 2
    SCOPUS = 3
    PUBMED = 4
    PMC = 5
    WEB_OF_SCIENCE = 6
    SPRINGER = 7

    nome = models.CharField("Nome", max_length=255)

    class Meta:
        db_table = 'main_bases'
        verbose_name = 'Base'
        verbose_name_plural = 'Base'

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome

@reversion.register()
class Documento(BaseModel):
    """ Documentos das revisões  """
    bases = models.ManyToManyField(Base)

    titulo = models.CharField("Titulo", max_length=2048)
    resumo = models.TextField("Resumo")
    resumo_url = models.TextField("URL Resumo", null=True, blank=True)
    autores = models.TextField("Autores", null=True, blank=True)
    revista = models.CharField("Revista", max_length=255, null=True, blank=True)
    citado_papers = models.IntegerField("Número de papers que citaram o artigo",
                                        null=True, blank=True)
    citado_patentes = models.IntegerField("Número de patentes que citaram o artigo",
                                         null=True, blank=True)
    doi = models.CharField("DOI", max_length=255, null=True, blank=True)

    html_url = models.CharField("Nome completo de um autor", max_length=255,
                                null=True, blank=True)
    palavras_chaves = models.TextField("Palavra chaves", null=True, blank=True)

    pdf_url	= models.CharField("URL do pdf", max_length=255, null=True, blank=True)
    data = models.DateField("Data da publicação", null=True, blank=True)
    rank = models.IntegerField("Rank do artigo na pesquisa", null=True, blank=True)
    citado_papers_scholar = models.IntegerField("Número de citações pelo Google Scholar", null=True, blank=True)
    citado_papers_scholar_data = models.DateTimeField("Data de verificação no Google Scholar", null=True, blank=True)

    arquivo = models.FileField(
        upload_to='arquivos', verbose_name='Arquivo do documento', 
        blank=True, null=True)

    class Meta:
        db_table = 'main_documentos'
        verbose_name = 'Documento'
        verbose_name_plural = 'Documentos'
        unique_together = (("titulo", "doi"),)

    @property
    def lista_fichamentos_revisoes(self):
        return list(Fichamento.objects.filter(documento=self.id).values_list('revisao__id', flat=True))

    @property
    def dicionario_fichamentos_revisoes(self):
        fichamentos = Fichamento.objects.filter(documento=self.id).values_list('revisao__id', 'id')
        if fichamentos: 
            return dict(fichamentos)

    @property
    def bases_string(self):
        return ','.join([a.nome for a in self.bases.all()])

    def __unicode__(self):
        return self.titulo

    def __str__(self):
        return self.titulo

@reversion.register()
class Revisao(BaseModel):
    """ Revisões Bibliográficas """
    nome = models.CharField("Nome", max_length=90)
    descricao = models.TextField("Descricao")
    usuarios = models.ManyToManyField(Usuario, related_name="revisoes")
    adm = models.ForeignKey(Usuario, related_name='adm_revisoes', on_delete=models.CASCADE)
    documentos = models.ManyToManyField(Documento, related_name='revisoes')

    class Meta:
        db_table = 'main_revisoes'
        verbose_name = 'Revisão'
        verbose_name_plural = 'Revisões'

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome


class Tag(BaseModel):
    nome = models.CharField("Nome", max_length=20)
    cor = models.CharField("Cor", max_length=7)

    revisao = models.ForeignKey(Revisao, on_delete=models.CASCADE)


    class Meta:
        db_table = 'main_tags'
        verbose_name = 'Tag'
        verbose_name_plural = 'Tag'

    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome


@reversion.register()
class Fichamento(BaseModel):
    documento = models.ForeignKey(Documento, on_delete=models.CASCADE, related_name="fichamentos")
    revisao = models.ForeignKey(Revisao, on_delete=models.CASCADE, related_name="fichamentos")
    caracteristicas_dados = MartorField("Características dos dados analisados", blank=True)
    citacoes = MartorField("Citações", blank=True)
    anotacoes = MartorField("Anotações gerais", blank=True)

    tags = models.ManyToManyField(Tag, related_name="fichamentos")

    class Meta:
        db_table = 'main_fichamentos'
        verbose_name = 'fichamentos'
        verbose_name_plural = 'fichamentos'

    def __unicode__(self):
        return self.documento.titulo

    def __str__(self):
        return self.documento.titulo 

atena/apps/base/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import re

from django import forms
from django.utils import timezone
from localflavor.br.forms import BRCPFField


class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.usuario = kwargs.pop('usuario')
        super(BaseForm, self).__init__(*args, **kwargs)
        if 'cadastrado_por' in self.fields:
            self.fields['cadastrado_por'].required = False

    def save(self, commit=True):
        objeto = super(BaseForm, self).save(commit=False)
        objeto.cadastrante = self.usuario
        if self.instance.id is not None:
            objeto.atualizado_em = timezone.now()

        if commit:
            objeto.save()
            self.save_m2m()

        return objeto


class BRCPFFieldUnique(BRCPFField):
    """
    Extende a classe BRCPFField para forçar valores
    únicos para o CPF e também para sempre salvar apenas
    os números na base de dados sem pontos e hífem.
    Usado no UserRegistrationForm que não extende o ModelForm
    e por isso ignora o fato do campo cpf estar marcado como único.
    """

    default_error_messages = {
        'invalid': "Número de CPF inválido.",
        'max_digits': "Este campo requer no máximo 11 dígitos ou 14 caracteres.",
    }

    def __init__(self, *args, **kwargs):
        super(BRCPFFieldUnique, self).__init__(*args, **kwargs)

    def clean(self, value):
        value = re.sub("[-\.]", "", value)

        if value == '00000000000':
            return value

        super(BRCPFFieldUnique, self).clean(value)

        return value


class RGField(forms.CharField):

    def clean(self, value):
        value = str(value)
        value = re.sub("[()-\.]", "", value)
        return value


class TelefoneField(RGField):
    pass

atena/apps/base/views.py
# -*- coding: utf-8 -*-
from django.core.paginator import EmptyPage, PageNotAnInteger
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.base import TemplateView
from django.shortcuts import HttpResponseRedirect
from django.db import transaction

from base.diggpagination import DiggPaginator as Paginator
from .mixins import *


class BaseTemplateView(TemplateView):
    template = ""
    titulo_pagina = ""
    subtitulo_pagina = ""

    def get_context_data(self, **kwargs):
        self.template_name = self.template
        context = super(BaseTemplateView, self).get_context_data(**kwargs)
        context['titulo_pagina'] = self.titulo_pagina
        context['subtitulo_pagina'] = self.subtitulo_pagina

        return context


class BaseFormView(LoginRequiredMixin, CreateView):
    template_name = 'main/cadastro.html'
    subtitulo_pagina = 'Cadastrar'
    success_url = '/sucesso/'

    def get_context_data(self, **kwargs):
        context = super(BaseFormView, self).get_context_data(**kwargs)
        context['titulo_pagina'] = self.titulo_pagina
        context['subtitulo_pagina'] = self.subtitulo_pagina
        return context

    def get_form_kwargs(self):
        kwargs = super(BaseFormView, self).get_form_kwargs()
        kwargs.update({'usuario': self.request.user})

        return kwargs

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        return super(BaseFormView, self).post(request, *args, **kwargs)


class BaseUpdateView(BaseFormView, UpdateView):
    subtitulo_pagina = ''

    def post(self, request, *args, **kwargs):
        if request.POST.get('reset', None) == 'Excluir':
            self.get_object().delete()
            return HttpResponseRedirect(self.success_url)

        else:
            return super(BaseUpdateView, self).post(request, *args, **kwargs)


class BaseListView(LoginRequiredMixin, TemplateView):
    template_name = "base/lista.html"
    subtitulo_pagina = "Lista"
    filtro = None
    entrada_atual_filtro = ""
    queryset = []
    paginate_by = 64
    titulo_pagina = ""

    def get_queryset(self):
        return self.queryset

    def get(self, *args, **kwargs):
        if self.filtro:
            filtro = self.filtro(self.request.GET or None, queryset=self.get_queryset())
            if filtro.is_valid():
                self.queryset = filtro.pesquisar()
                self.entrada_atual_filtro = filtro['entrada'].value()
            else:
                self.queryset = self.get_queryset()

        return super(BaseListView, self).get(*args, **kwargs)


    def get_context_data(self, **kwargs):
        paginator = Paginator(self.get_queryset(), self.paginate_by, tail=4, body=3)
        pagina = self.request.GET.get('pagina', 1)

        try:
            lista = paginator.page(pagina)
        except PageNotAnInteger:
            lista = paginator.page(1)
        except EmptyPage:
            lista = paginator.page(paginator.num_pages)

        GET_params = self.request.GET.copy()
        if 'pagina' in GET_params.keys():
            del GET_params['pagina']

        return {
            'GET_params': GET_params,
            'lista': lista,
            'filtro': self.filtro,
            'entrada_atual_filtro': self.entrada_atual_filtro,
            'titulo_pagina': self.titulo_pagina,
        }

atena/apps/contas/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic import FormView, RedirectView
from django.views.generic.edit import CreateView
from django.shortcuts import get_object_or_404
from django.contrib.auth import login, logout
from django.utils.http import is_safe_url
from django.shortcuts import render

from base.views import BaseFormView, BaseUpdateView, TemplateView
from base.mixins import LoginRequiredMixin
from .forms import LoginForm, UsuarioForm
from .models import Usuario

class LoginView(FormView):
    template_name = 'contas/login.html'
    form_class = LoginForm
    success_url = '/'
    redirect_field_name = 'next'

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        return context

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)

        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url

        return redirect_to

    def form_valid(self, form):
        if form.is_valid():
            if not form.cleaned_data['lembrar_me']:
                self.request.session.set_expiry(0)
            login(self.request, form.obter_usuario())
        return super(LoginView, self).form_valid(form)


class LogoutView(LoginRequiredMixin, RedirectView):
    url = '/contas/login/'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class CadastroUsuarioView(BaseFormView):
    titulo_pagina = "Usuário"
    subtitulo_pagina = 'Cadastrar'
    model = Usuario
    form_class = UsuarioForm


class AutoCadastroUsuarioView(CreateView):
    template_name = 'contas/registrar-se.html'
    model = Usuario
    form_class = UsuarioForm
    success_url = '/'


class EdicaoUsuarioView(CadastroUsuarioView, BaseUpdateView):
    subtitulo_pagina = 'Editar'

    def get_queryset(self):
        if self.request.user.has_group('Administrador'):
            return Usuario.objects.all()
        else:
            return Usuario.objects.filter(id=self.request.user.id)


class ProfileView(TemplateView):
    template_name = 'contas/profile.html'

    def get_object(self):
        return get_object_or_404(Usuario, id=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)

        context.update({
            'obj': self.get_object(),
        })

        return context

atena/templates/main/includes/artigos-revisoes-control-sidebar.html
{% load staticfiles %}

<aside class="control-sidebar control-sidebar-dark control-sidebar">
<!-- Create the tabs -->
<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
  <li class="active"><a href="#control-sidebar-theme-demo-options-tab" data-toggle="tab" aria-expanded="true"><i class="fa fa-tag"></i></a></li>
  <li class=""><a href="#control-sidebar-home-tab" data-toggle="tab" aria-expanded="false"><i class="fa fa-home"></i></a></li>
</ul>
<!-- Tab panes -->
<div class="tab-content">
  <!-- Home tab content -->
  <div class="tab-pane" id="control-sidebar-home-tab">
    <h3 class="control-sidebar-heading">Recent Activity</h3>
    <ul class="control-sidebar-menu">
      <li>
        <a href="javascript:void(0)">
          <i class="menu-icon fa fa-birthday-cake bg-red"></i>

          <div class="menu-info">
            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

            <p>Will be 23 on April 24th</p>
          </div>
        </a>
      </li>
      <li>
        <a href="javascript:void(0)">
          <i class="menu-icon fa fa-user bg-yellow"></i>

          <div class="menu-info">
            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

            <p>New phone +1(800)555-1234</p>
          </div>
        </a>
      </li>
      <li>
        <a href="javascript:void(0)">
          <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

          <div class="menu-info">
            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

            <p>nora@example.com</p>
          </div>
        </a>
      </li>
      <li>
        <a href="javascript:void(0)">
          <i class="menu-icon fa fa-file-code-o bg-green"></i>

          <div class="menu-info">
            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

            <p>Execution time 5 seconds</p>
          </div>
        </a>
      </li>
    </ul>
    <!-- /.control-sidebar-menu -->

    <h3 class="control-sidebar-heading">Tasks Progress</h3>
    <ul class="control-sidebar-menu">
      <li>
        <a href="javascript:void(0)">
          <h4 class="control-sidebar-subheading">
            Custom Template Design
            <span class="label label-danger pull-right">70%</span>
          </h4>

          <div class="progress progress-xxs">
            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
          </div>
        </a>
      </li>
      <li>
        <a href="javascript:void(0)">
          <h4 class="control-sidebar-subheading">
            Update Resume
            <span class="label label-success pull-right">95%</span>
          </h4>

          <div class="progress progress-xxs">
            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
          </div>
        </a>
      </li>
      <li>
        <a href="javascript:void(0)">
          <h4 class="control-sidebar-subheading">
            Laravel Integration
            <span class="label label-warning pull-right">50%</span>
          </h4>

          <div class="progress progress-xxs">
            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
          </div>
        </a>
      </li>
      <li>
        <a href="javascript:void(0)">
          <h4 class="control-sidebar-subheading">
            Back End Framework
            <span class="label label-primary pull-right">68%</span>
          </h4>

          <div class="progress progress-xxs">
            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
          </div>
        </a>
      </li>
    </ul>
    <!-- /.control-sidebar-menu -->

  </div>
    <div id="control-sidebar-theme-demo-options-tab" class="tab-pane active">
        <div>
            <div class="input-group-btn">
              <a class="btn btn-default" style="width: 200px;" href="{% url 'main:CadastroDocumentoRevisao' revisao.id %}">
                Add um artigo
              </a>
            </div> 
            <br>           
            <div class="input-group-btn">
              <a class="btn btn-default" style="width: 200px;" href="{% url 'main:ImportarDocumentos' revisao.id %}">   
                Importar Artigos das Bases
              </a>
            </div>
            <br>
            <div class="input-group-btn">
              <a class="btn btn-default" href="{% url 'main:ClassificarDocumentos' revisao.id %}">Classificar artigos via Scholar</a>
            </div>
            <h4 class="control-sidebar-heading">Add Tag</h4>
            <form id="tag_form" method="POST" action="{% url 'main:CadastroTag' revisao.id%}" >
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_nome">Nome</label>
                    <input type="text" name="nome" id="id_nome" class="form-control">
                </div>
                <div class="form-group">
                    <label for="id_cor">Cor: </label>
                    <input type="text" name="cor" id="id_cor" class="my-colorpicker1 colorpicker-element form-control">
                </div>
                <button type="submit" class="btn btn-primary pull-right">Adicionar</button>
            </form>
        </div>
        <br>
        <div id="lista_tags">
            <h4 class="control-sidebar-heading">Tags</h4>
            {% for tag in lista_tags%}
            <button data-id="{{tag.id}}" class="btn mb-10 btntag" style="background-color: {{tag.cor}}; width:200px; color:white;"> {{tag.nome}} </button>

            {% endfor %}
        </div>
    </div>
  <!-- /.tab-pane -->


</div>
</aside>

<script>
    $(document).on("submit", "#tag_form", function(e) {
        e.preventDefault();
        var self = $(this),
            url = self.attr("action"),
            ajax_req = $.ajax({
                url: url,
                type: "POST",
                data: {
                    nome: self.find("#id_nome").val(),
                    cor: self.find("#id_cor").val()
                },
                success: function(data, textStatus, jqXHR) {
                    console.log('uc', data, textStatus, jqXHR);
                    estilo = "width:200px; background-color:" + data.tag.cor;

                    button = $('<button data-id='+data.tag.id+' class="btn mb-10 btntag" style='+estilo+'>'+data.tag.nome+'</button>');
                    $('#lista_tags').append(button);
                },
                error: function(data, textStatus, jqXHR) {
                    alert("erro");
                    var errors = $.parseJSON(data.responseText);
                    $.each(errors, function(index, value) {
                        if (index === "__all__") {
                            django_message(value[0], "error");
                        } else {
                            apply_form_field_error(index, value);
                        }
                    });
                }
            });
    });

        $(document).on("click", ".btntag", function(e) {
            id = $(this).attr('data-id');

            var idSelector = function () {
                return parseInt(this.id);
            };
            docIds = $(".doc-selected:checked").map(idSelector).get();
            var idObj = function (v) {
                return {name: 'docs[]', value: v};
            };

            if (docIds.length > 0) {
                if (confirm('Associar/desassociar os fichamentos selecionados com a tag "'+$(this).text()+'"?')) {
                    docIds = docIds.map(idObj);
                    docIds.push({name: 'csrfmiddlewaretoken', value: jQuery("[name=csrfmiddlewaretoken]").val()});
                    docIds.push({name: 'id', value: id});
                    submit("{% url 'main:AssociarTag' revisao.id %}?", 'POST', docIds);
                }
            } else {
                params = [{name: 'tag', value: id}];
                submit("{% url 'main:ListaDocumentosRevisao' revisao.id %}?", 'GET', params);
            }

        });


    //Colorpicker
    $('.my-colorpicker1').colorpicker()
</script>