atena/apps/contas/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [

    url(r'login/$', LoginView.as_view(), name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),
    url(r'usuario/registrar-se/$', AutoCadastroUsuarioView.as_view(), name='autocadastro'),
    url(r'usuario/editar/(?P<pk>\d+)/$', EdicaoUsuarioView.as_view(),
        name='EdicaoUsuario'),
    url(r'usuario/profile/(?P<pk>\d+)/$', ProfileView.as_view(),
        name='Profile'),
]

atena/apps/main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import *

urlpatterns = [

    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^sucesso/$', SucessoView.as_view(), name='Sucesso'),
    url(r'^revisao/add/$', CadastroRevisaoView.as_view(), name='CadastroRevisao'),
    url(r'^revisao/lista/$', ListaRevisoesView.as_view(), name='ListaRevisoes'),
    url(r'^revisao/(?P<pk>\d+)/$', EdicaoRevisaoView.as_view(), name='EdicaoRevisao'),
    url(r'^revisao/(?P<pk>\d+)/artigos$', ListaDocumentosRevisaoView.as_view(), name='ListaDocumentosRevisao'),
    url(r'^revisao/(?P<pk>\d+)/documentos/(?P<pk_documento>\d+)/$', VisualizaDocumentoView.as_view(), name='VisualizarDocumento'),
    url(r'^revisao/(?P<revisao_pk>\d+)/documento/add/$', CadastroDocumentoRevisaoView.as_view(), name='CadastroDocumentoRevisao'),
    url(r'^revisao/(?P<pk>\d+)/documentos/importar/$', ImportarDocumentosView.as_view(), name='ImportarDocumentos'),
    url(r'^revisao/(?P<pk>\d+)/documentos/remover/$', RemoverDocumentoRevisaoView.as_view(), name='RemoverDocumentos'),
    url(r'^revisao/(?P<pk>\d+)/documentos/classificar/$', ClassificarDocumentosView.as_view(), name='ClassificarDocumentos'),
    url(r'^revisao/(?P<revisao_pk>\d+)/documento/fichamento/add/(?P<documento_pk>\d+)$',
        CadastroFichamentoView.as_view(), name='CadastroFichamento'),
    url(r'^revisao/(?P<revisao_pk>\d+)/documento/(?P<documento_pk>\d+)/fichamento/(?P<pk>\d+)$',
        EdicaoFichamentoView.as_view(), name='EdicaoFichamento'),

    url(r'^revisao/(?P<revisao_pk>\d+)/documentos/tags/add/$', CadastroTagView.as_view(), name='CadastroTag'),
    url(r'^revisao/(?P<revisao_pk>\d+)/documentos/tags/associar/$', AssociarTagView.as_view(), name='AssociarTag'),

]

atena/urls.py
"""atena URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
"""

from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^martor/', include('martor.urls')),
    url(r'^', include(('main.urls', 'main'), namespace='main')),
    url(r'^contas/', include(('contas.urls', 'contas'), namespace='contas')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'main.views.handler404'
handler403 = 'main.views.handler403'
handler500 = 'main.views.handler500'

atena/apps/base/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class BaseModel(models.Model):
    cadastrado_em = models.DateTimeField("Data de cadastrado", auto_now_add=True)
    cadastrado_por = models.ForeignKey('contas.Usuario', default=1, on_delete=models.CASCADE)
    atualizado_em = models.DateTimeField("Data da última atualizacao", auto_now=True)

    class Meta:
        abstract = True

atena/apps/base/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import re

from django import forms
from django.utils import timezone
from localflavor.br.forms import BRCPFField


class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.usuario = kwargs.pop('usuario')
        super(BaseForm, self).__init__(*args, **kwargs)
        if 'cadastrado_por' in self.fields:
            self.fields['cadastrado_por'].required = False

    def save(self, commit=True):
        objeto = super(BaseForm, self).save(commit=False)
        objeto.cadastrante = self.usuario
        if self.instance.id is not None:
            objeto.atualizado_em = timezone.now()

        if commit:
            objeto.save()
            self.save_m2m()

        return objeto


class BRCPFFieldUnique(BRCPFField):
    """
    Extende a classe BRCPFField para forçar valores
    únicos para o CPF e também para sempre salvar apenas
    os números na base de dados sem pontos e hífem.
    Usado no UserRegistrationForm que não extende o ModelForm
    e por isso ignora o fato do campo cpf estar marcado como único.
    """

    default_error_messages = {
        'invalid': "Número de CPF inválido.",
        'max_digits': "Este campo requer no máximo 11 dígitos ou 14 caracteres.",
    }

    def __init__(self, *args, **kwargs):
        super(BRCPFFieldUnique, self).__init__(*args, **kwargs)

    def clean(self, value):
        value = re.sub("[-\.]", "", value)

        if value == '00000000000':
            return value

        super(BRCPFFieldUnique, self).clean(value)

        return value


class RGField(forms.CharField):

    def clean(self, value):
        value = str(value)
        value = re.sub("[()-\.]", "", value)
        return value


class TelefoneField(RGField):
    pass

atena/apps/contas/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import authenticate

from base.forms import *
from .helpers import *
from .models import *


class LoginForm(forms.Form):
    cpf = forms.CharField(label='cpf', required=True)
    senha = forms.CharField(label='Senha', required=False)
    lembrar_me = forms.BooleanField(label="Manter conectado", required=False)

    def clean(self):
        if self.errors:
            return super(LoginForm, self).clean()

        usuarios = Usuario.objects.filter(cpf=self.cleaned_data['cpf'])
        self.usuario = authenticate(username=self.cleaned_data.get('cpf', None), password=self.cleaned_data['senha'])

        if usuarios.count() == 0:
            self.add_error('cpf', u'Nenhum usuário cadastrado com esse usuário')

        if (not self.usuario or not self.usuario.ativo == 1) and self.cleaned_data.get('cpf', None):
            self.add_error('senha', u'Senha incorreta')

        return super(LoginForm, self).clean()

    def obter_usuario(self):
        return self.usuario


class UsuarioForm(forms.ModelForm):
    senha = forms.CharField(label=u'Senha', widget=forms.PasswordInput)
    senha2 = forms.CharField(label=u'Confirmação da senha', widget=forms.PasswordInput)
    imagem = forms.ImageField(required=False)

    class Meta:
        model = Usuario
        exclude = ['password', 'ativo', 'admin', 'superusuario', 'last_login']

    def __init__(self, *args, **kwargs):
        super(UsuarioForm, self).__init__(*args, **kwargs)
        self.helper = UsuarioHelper()
        if self.instance.pk:
            self.fields['senha'].required = False
            self.fields['senha2'].required = False

    def clean_senha2(self):
        senha = self.cleaned_data["senha"]
        senha2 = self.cleaned_data["senha2"]
        if senha != senha2:
            raise forms.ValidationError(u"As senhas não são iguais")

    def save(self, commit=True):
        objeto = super(UsuarioForm, self).save(commit=False)
        if self.cleaned_data["senha"]:
            objeto.set_password(self.cleaned_data["senha"])

        if self.cleaned_data['imagem']:
            objeto.imagem = self.cleaned_data['imagem']

        if commit:
            objeto.save()

        return objeto

atena/apps/main/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from .helpers import RevisaoHelper, FichamentoHelper, SelecionarBaseHelper, DocumentoHelper
from .models import Revisao, Documento, Fichamento, Tag
from base.forms import BaseForm


class RevisaoForm(BaseForm):

    class Meta:
        model = Revisao
        exclude = ['adm', 'documentos']

    def __init__(self, *args, **kwargs):
        super(RevisaoForm, self).__init__(*args, **kwargs)
        self.helper = RevisaoHelper()

    def save(self, commit=True):
        revisao = super(RevisaoForm, self).save(commit=False)
        revisao.adm = self.usuario
        if commit:
            revisao.save()
            self.save_m2m()

            if self.usuario not in revisao.usuarios.all():
                revisao.usuarios.add(self.usuario)

        return revisao


class DocumentoForm(BaseForm):
    class Meta:
        model = Documento
        exclude = ['revisao','arquivo']

    def __init__(self, *args, **kwargs):
        self.revisao = kwargs.pop('revisao')
        super(DocumentoForm, self).__init__(*args, **kwargs)
        self.helper = DocumentoHelper()

    def save(self, commit=True):
        documento = super(DocumentoForm, self).save(commit=False)
        

        if commit:
            documento.save()
            self.save_m2m()
            if self.revisao: 
                self.revisao.documentos.add(documento)

        return documento


class FichamentoForm(BaseForm):

    class Meta:
        model = Fichamento
        exclude = ['documento', 'revisao']

    def __init__(self, *args, **kwargs):
        self.revisao = kwargs.pop('revisao')
        self.documento = kwargs.pop('documento')
        super(FichamentoForm, self).__init__(*args, **kwargs)
        self.fields['tags'].queryset = Tag.objects.filter(revisao=self.revisao)
        self.fields['tags'].required = False
        self.helper = FichamentoHelper()


    def save(self, commit=True):
        fichamento = super(FichamentoForm, self).save(commit=False)
        fichamento.documento = self.documento
        fichamento.revisao = self.revisao
        
        if commit:
            fichamento.save()
            self.save_m2m()


        return fichamento


class TagForm(BaseForm):
    class Meta:
        model = Tag
        fields = ['nome', 'cor']

    def __init__(self, *args, **kwargs):
        self.revisao = kwargs.pop('revisao')
        super(TagForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        tag = super(TagForm, self).save(commit=False)
        tag.revisao = self.revisao

        if commit:
            tag.save()

        return tag


class SelecionarBaseForm(forms.Form):
    termos_de_tecnologias = forms.CharField(required=False)
    termos_da_saude = forms.CharField(required=False)
    revistas = forms.CharField(required=False)
    ano_inicio = forms.IntegerField(required=False)
    ano_fim = forms.IntegerField(required=False)
    extra = forms.CharField(required=False)
    bases_de_pesquisa = forms.MultipleChoiceField(
        choices=(
            ('IEEE Xplore', 'IEEE Xplore'),
            ('Scopus', 'Scopus'),
            ('Web of Science', 'Web of Science'),
            ('Springer', 'Springer'),
            ('Science Direct', 'Science Direct'),
            ('PMC', 'PMC'),
            ('PubMed', 'PubMed')
        ),
        widget=forms.CheckboxSelectMultiple()
    )
    revisao = forms.IntegerField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super(SelecionarBaseForm, self).__init__(*args, **kwargs)
        self.helper = SelecionarBaseHelper()

atena/apps/base/views.py
# -*- coding: utf-8 -*-
from django.core.paginator import EmptyPage, PageNotAnInteger
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.base import TemplateView
from django.shortcuts import HttpResponseRedirect
from django.db import transaction

from base.diggpagination import DiggPaginator as Paginator
from .mixins import *


class BaseTemplateView(TemplateView):
    template = ""
    titulo_pagina = ""
    subtitulo_pagina = ""

    def get_context_data(self, **kwargs):
        self.template_name = self.template
        context = super(BaseTemplateView, self).get_context_data(**kwargs)
        context['titulo_pagina'] = self.titulo_pagina
        context['subtitulo_pagina'] = self.subtitulo_pagina

        return context


class BaseFormView(LoginRequiredMixin, CreateView):
    template_name = 'main/cadastro.html'
    subtitulo_pagina = 'Cadastrar'
    success_url = '/sucesso/'

    def get_context_data(self, **kwargs):
        context = super(BaseFormView, self).get_context_data(**kwargs)
        context['titulo_pagina'] = self.titulo_pagina
        context['subtitulo_pagina'] = self.subtitulo_pagina
        return context

    def get_form_kwargs(self):
        kwargs = super(BaseFormView, self).get_form_kwargs()
        kwargs.update({'usuario': self.request.user})

        return kwargs

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        return super(BaseFormView, self).post(request, *args, **kwargs)


class BaseUpdateView(BaseFormView, UpdateView):
    subtitulo_pagina = ''

    def post(self, request, *args, **kwargs):
        if request.POST.get('reset', None) == 'Excluir':
            self.get_object().delete()
            return HttpResponseRedirect(self.success_url)

        else:
            return super(BaseUpdateView, self).post(request, *args, **kwargs)


class BaseListView(LoginRequiredMixin, TemplateView):
    template_name = "base/lista.html"
    subtitulo_pagina = "Lista"
    filtro = None
    entrada_atual_filtro = ""
    queryset = []
    paginate_by = 64
    titulo_pagina = ""

    def get_queryset(self):
        return self.queryset

    def get(self, *args, **kwargs):
        if self.filtro:
            filtro = self.filtro(self.request.GET or None, queryset=self.get_queryset())
            if filtro.is_valid():
                self.queryset = filtro.pesquisar()
                self.entrada_atual_filtro = filtro['entrada'].value()
            else:
                self.queryset = self.get_queryset()

        return super(BaseListView, self).get(*args, **kwargs)


    def get_context_data(self, **kwargs):
        paginator = Paginator(self.get_queryset(), self.paginate_by, tail=4, body=3)
        pagina = self.request.GET.get('pagina', 1)

        try:
            lista = paginator.page(pagina)
        except PageNotAnInteger:
            lista = paginator.page(1)
        except EmptyPage:
            lista = paginator.page(paginator.num_pages)

        GET_params = self.request.GET.copy()
        if 'pagina' in GET_params.keys():
            del GET_params['pagina']

        return {
            'GET_params': GET_params,
            'lista': lista,
            'filtro': self.filtro,
            'entrada_atual_filtro': self.entrada_atual_filtro,
            'titulo_pagina': self.titulo_pagina,
        }

atena/apps/contas/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic import FormView, RedirectView
from django.views.generic.edit import CreateView
from django.shortcuts import get_object_or_404
from django.contrib.auth import login, logout
from django.utils.http import is_safe_url
from django.shortcuts import render

from base.views import BaseFormView, BaseUpdateView, TemplateView
from base.mixins import LoginRequiredMixin
from .forms import LoginForm, UsuarioForm
from .models import Usuario

class LoginView(FormView):
    template_name = 'contas/login.html'
    form_class = LoginForm
    success_url = '/'
    redirect_field_name = 'next'

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        return context

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)

        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url

        return redirect_to

    def form_valid(self, form):
        if form.is_valid():
            if not form.cleaned_data['lembrar_me']:
                self.request.session.set_expiry(0)
            login(self.request, form.obter_usuario())
        return super(LoginView, self).form_valid(form)


class LogoutView(LoginRequiredMixin, RedirectView):
    url = '/contas/login/'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class CadastroUsuarioView(BaseFormView):
    titulo_pagina = "Usuário"
    subtitulo_pagina = 'Cadastrar'
    model = Usuario
    form_class = UsuarioForm


class AutoCadastroUsuarioView(CreateView):
    template_name = 'contas/registrar-se.html'
    model = Usuario
    form_class = UsuarioForm
    success_url = '/'


class EdicaoUsuarioView(CadastroUsuarioView, BaseUpdateView):
    subtitulo_pagina = 'Editar'

    def get_queryset(self):
        if self.request.user.has_group('Administrador'):
            return Usuario.objects.all()
        else:
            return Usuario.objects.filter(id=self.request.user.id)


class ProfileView(TemplateView):
    template_name = 'contas/profile.html'

    def get_object(self):
        return get_object_or_404(Usuario, id=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)

        context.update({
            'obj': self.get_object(),
        })

        return context

atena/templates/main/listas/artigos_revisao.html
{% extends 'base/lista.html' %}
{% load poll_extras %}
{% load extras %}
{% load staticfiles %}

{% block extra_table_head %}
<div class="box-tools">
  <div class="input-group input-group-sm mr-10" style="width: 150px;">
    <div class="input-group-btn">
      <a class="btn btn-default" id="delete-from-review" href="#">Remover artigos selecionados da revisão</a>
    </div>
    <div class="input-group-btn">
      <a class="btn btn-default pull-right" style="width: 100px;" data-toggle="control-sidebar"  href="#">Ações <i class="fa fa-gears"></i></a>
    </div>
  </div>
</div>
{% endblock extra_table_head%}

{% block tabela %}
{% csrf_token %}
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><input type="checkbox" id="select-all"></th>
      <th>Titulo</th>
      <th>Base</th>
      <th>Fichamento</th>
      <th>Citações Scholar</th>
    </tr>
  </thead>
  <tbody>
    {% for  obj in lista %}
      <tr>
        <td><input type="checkbox" class="doc-selected" id="{{ obj.id }}" /></td>
        <td>
            {% for tag in obj|tags:revisao %}
              <span class="tag" title="{{tag.nome}}" style="background-color: {{tag.cor}}"></span>
              {% if forloop.last %} <br> {% endif %}
            {% endfor %}

            <a href="{% url 'main:VisualizarDocumento' revisao.id obj.id %}"> {{ obj.titulo }} </a>
        </td>
        <td> {{ obj.bases_string }} </td>
        <td> 
          {% if revisao.id in obj.lista_fichamentos_revisoes %}
            <a href="{% url 'main:EdicaoFichamento' revisao.id obj.id  obj.dicionario_fichamentos_revisoes|get_item:revisao.id %}"> abrir </a> 
          {% else %} 
            <a href="{% url 'main:CadastroFichamento' revisao.id obj.id  %}"> Começar fichamento </a> 
          {% endif %} 
        </td>
        <td>{{ obj.citado_papers_scholar }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock tabela %}

{% block extra_html %}
    {% include 'main/includes/artigos-revisoes-control-sidebar.html' %}
<div class="colorpicker dropdown-menu colorpicker-with-alpha colorpicker-right colorpicker-hidden" style="top: 993px; left: 623px;"><div class="colorpicker-saturation" style="background-color: rgb(255, 0, 0);"><i style="left: 78.6517px; top: 65.098px;"><b></b></i></div><div class="colorpicker-hue"><i style="top: 100px;"></i></div><div class="colorpicker-alpha" style="background-color: rgb(89, 19, 19);"><i style="top: 0px;"></i></div><div class="colorpicker-color" style="background-color: rgb(89, 19, 19);"><div style="background-color: rgb(89, 19, 19);"></div></div><div class="colorpicker-selectors"></div></div>
<div class="colorpicker dropdown-menu colorpicker-with-alpha colorpicker-right colorpicker-hidden" style="top: 1269px; left: 93px;"><div class="colorpicker-saturation" style="background-color: rgb(127, 0, 255);"><i style="left: 83.4101px; top: 14.902px;"><b></b></i></div><div class="colorpicker-hue"><i style="top: 25.046px; left: 0px;"></i></div><div class="colorpicker-alpha" style="background-color: rgb(126, 36, 217);"><i style="top: 0px;"></i></div><div class="colorpicker-color" style="background-color: rgb(126, 36, 217);"><div style="background-color: rgb(126, 36, 217);"></div></div><div class="colorpicker-selectors"></div></div>
{% endblock extra_html %}


{% block extra_js %}
    <script type="text/javascript">
      function typeOf(obj) {
      return {}.toString.call(obj).split(' ')[1].slice(0, -1).toLowerCase();
      }

  function submit(action, method, values) {
    var form = $('<form/>', {
        action: action,
        method: method
    });
    $.each(values, function() {
        form.append($('<input/>', {
            type: 'hidden',
            name: this.name,
            value: this.value
        }));
    });
    form.appendTo('body').submit();
}


  $(document).ready(function() {
    changeFunc = function() {
        console.log('trigger');
        var idSelector = function() { return parseInt(this.id); };
        docIds = $(".doc-selected:checked").map(idSelector).get() ;
    };
    $("#select-all").click(function() {
        $(".doc-selected").prop('checked', $(this).is(':checked'));
    });

    $("#delete-from-review").click(function(e) {
        if (confirm('Você tem certeza que quer remover os artigos e fichamentos selecionados?')){
            var idSelector = function () {
                return parseInt(this.id);
            };
            docIds = $(".doc-selected:checked").map(idSelector).get();
            var idObj = function (v) {
                return {name: 'docs[]', value: v};
            };
            docIds = docIds.map(idObj);
            docIds.push({name: 'csrfmiddlewaretoken', value: jQuery("[name=csrfmiddlewaretoken]").val()});
            submit("{% url 'main:RemoverDocumentos' revisao.id %}?", 'POST', docIds);
        }
        e.preventDefault();
    });
});

    </script>

    <script src="{%  static 'admin-lte/bower_components/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js' %}"></script>
{% endblock extra_js %}

{% block extra_css %}
  <link rel="stylesheet" href="{% static 'admin-lte/bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css' %}">
{% endblock %}

atena/templates/main/listas/revisoes.html
{% extends 'base/lista.html' %}

{% block extra_table_head %}
<div class="box-tools">
  <div class="input-group input-group-sm mr-10" style="width: 150px;">
    <div class="input-group-btn">
      <a class="btn btn-default pull-right" href="{% url 'main:CadastroRevisao' %}">Adicionar Nova</a>
    </div>
  </div>
</div>
{% endblock extra_table_head%}

{% block tabela %}
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for  obj in lista %}
      <tr>
        <td> <a href="{% url 'main:ListaDocumentosRevisao' obj.id %}"> {{ obj.nome }} </a></td>
        <td> {{ obj.descricao}} </td>
        <td class="td-editar"><a href="{% url 'main:EdicaoRevisao' obj.id %}">Editar</a></td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock tabela %}